server:
  port: 8084
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: mengan-web-demo
  profiles:
    active: @packaging@,alone
  cache:
    ehcache:
      config: ehcache/ehcache.xml
    type: redis
  redis:
    host: 120.24.22.59
    port: 6379
    database: 11
    password: 123456
    expireTime: 86400
    lettuce:
      pool:
        max-active: 16
        max-wait: 1s
        max-idle: 8
        min-idle: 4
  datasource:
    dynamic:
      primary: mysql1
      strict: true
      datasource:
        mysql1:
          url: jdbc:mysql://localhost:3306/ecip_api?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
          username: root
          password: 123456
          druid:
            initial-size: 1 #连接池初始化大小
            min-idle: 0 #最小空闲连接数
            max-active: 5 #最大连接数
            web-stat-filter:
              exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
            stat-view-servlet: #访问监控网页的登录用户名和密码
              login-username: druid
              login-password: druid
# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#elasticsearch:
#  host: 120.24.22.59
#  port: 9200
logging:
  level:
    root: DEBUG
